const name = 'snickers';
const age = 2;
const sentence = `my dog ${name} is ${age * 7} years old`;
console.log(sentence);
const person = 'Andrés';
const age = 10;
const sentence = `my dog ${name} is ${age * 1} years old`;
console.log(sentence);
const name = 'snickers';
const age = 2;
const sentence = `my dog ${name} is ${age * 7} years old`;
console.log(sentence);
const person = 'Gato';
const age = 10;
const sentence = `my dog ${name} is ${age * 4} years old`;
console.log(sentence);